UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Controllers/UsersController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsersAwardsApp.PLAttributes.Models;
using MimeTypes;
using System.Text;
using UsersAwardsApp.Entities;
using MvcSiteMapProvider;
using UsersAwardsApp.LogicContracts;
using UsersAwardsApp.LogicContracts.DTO;

namespace UsersAwardsApp.PLAttributes.Controllers
{
    [RoutePrefix("users")]
    [Route("~/user/{userId:int}/{action}")]
    public class UsersController : BaseController
    {
        public UsersController(IUserService userService, IAwardService awardService)
            :base(userService, awardService)
        {

        }

        // shouldn't be only numbers
        [Route(@"{term:regex(^[a-zA-Zа-яА-ЯёЁ_]{1}|([a-zA-Zа-яА-ЯёЁ\s_]+[0-9a-zA-Zа-яА-ЯёЁ\s_]*)$)?}/")]
        public ActionResult Index(string term)
        {
            IEnumerable<UserProfile> userDtos;
            if (!string.IsNullOrWhiteSpace(term))
            {
                SiteMaps.Current.CurrentNode.Description = string.Format("Search by \"{0}\"",term);
                userDtos = userService.FindAllByName(term);
            }
            else
            {
                userDtos = userService.GetUsers();
            }

            var users = Mapper.Map<IEnumerable<UserProfile>, IEnumerable<UserProfileViewModel>>(userDtos);
            return View(users);
        }

        [Route("~/award-users/{id:int}")]
        [HttpGet]
        public ActionResult UsersByAward(int id)
        {
            Award _award = awardService.GetAwardById(id);
            if(_award != null)
            {
                SiteMaps.Current.CurrentNode.ParentNode.Title = _award.Title;
                SiteMaps.Current.CurrentNode.Description = string.Format("Users with award \"{0}\"",_award.Title);
                return View("Index", Mapper.Map<IEnumerable<UserProfile>, IEnumerable<UserProfileViewModel>>(userService.GetUsersByAward(id)));
            }else
            {
                return HttpNotFound("Award not found");
            }
        }

        [Route(@"~/user/{term:length(1,50):regex(^[a-zA-Zа-яА-ЯёЁ_]{1}|([a-zA-Zа-яА-ЯёЁ\s_]+[0-9a-zA-Zа-яА-ЯёЁ\s_]*)$)}")]
        public ActionResult FindByName (string term)
        {
            UserProfile _user = userService.FindByName(term);
            if(_user != null)
            {
                UserProfileViewModel _userView = Mapper.Map<UserProfile, UserProfileViewModel>(_user);
                SiteMaps.Current.CurrentNode.Title = _user.Name;
                return View("UserPage", _userView);
            }
            return new HttpNotFoundResult("User not found");
        }

        [Route("~/user/{userId:int}")]
        public ActionResult UserPage(int userId)
        {
            UserProfile _user = userService.GetUserById(userId);
            if (_user != null)
            {
                SiteMaps.Current.CurrentNode.Title = _user.Name;
                return View(Mapper.Map<UserProfile, UserProfileViewModel>(_user));
            }
            else
                return HttpNotFound("User not found.");
        }

        [Route("~/create-user")]
        [HttpGet]
        public ActionResult CreateUser()
        {
            return View();
        }

        [Route("~/create-user")]
        [HttpPost]
        public ActionResult CreateUser(UserProfileViewModel model, HttpPostedFileBase file)
        {
            if(file != null)
            {
                string MimeType = file.ContentType;
                if (file != null && !MimeType.Contains("image"))
                    ModelState.AddModelError(nameof(model.Photo), "Images only allowed");
            }
            

            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    byte[] data = new byte[file.ContentLength];
                    file.InputStream.Read(data, 0, data.Length);
                    model.Photo = new ImageViewModel() { ImageData = data, Mime = file.ContentType };
                }

                var user = Mapper.Map<UserProfileViewModel, UserProfile>(model);
                userService.CreateUser(user);
                return RedirectToAction("Index");
            }
            else
                return View(model);

        }
        
        [ActionName("Edit")]
        public ActionResult Edit(int userId)
        {
            UserProfile userDto = userService.GetUserById(userId);
            if (userDto != null)
            {
                ViewBag.HasImage = (userDto.Photo != null) ? true : false;

                SiteMaps.Current.CurrentNode.ParentNode.Title = userDto.Name;
                var user = Mapper.Map<UserProfile, UserProfileViewModel>(userDto);
                return View(user);
            }
            else
                return HttpNotFound("User not found.");
        }
        [HttpPost]
        public ActionResult Edit(UserProfileViewModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    byte[] data = new byte[file.ContentLength];
                    file.InputStream.Read(data, 0, data.Length);
                    model.Photo = new ImageViewModel() { ImageData = data, Mime = file.ContentType };
                }

                if (userService.UpdateUser(Mapper.Map<UserProfileViewModel, UserProfile>(model))) {
                    return RedirectToAction("Index");
                }else
                {
                    return HttpNotFound("Error");
                }
            }
            else
                return View(model);
        }

        public ActionResult RemoveImage(int userId)
        {
            UserProfile userDto = userService.GetUserById(userId);
            if (userDto != null)
            {
                if (userDto.Photo == null)
                    return RedirectToAction("Edit", new { id = userId });

                userService.RemoveImage(userDto.Photo.Id);
                return RedirectToAction("Edit", new { id = userId });
            }
            else
                return HttpNotFound("User not found.");
        }


        [HttpGet]
        public ActionResult DeleteAjax(int userId)
        {
            if (!Request.IsAjaxRequest())
                return RedirectToAction("Delete", Request.RequestContext.RouteData.Values);

            UserProfile userDto = userService.GetUserById(userId);
            if(userDto == null)
                return HttpNotFound();

            if (userService.DeleteUser(userDto.Id)) {
                return Json(true, JsonRequestBehavior.AllowGet);
            }else
            {
                return HttpNotFound();
            }

        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult Delete(int userId)
        {
            UserProfile userDto = userService.GetUserById(userId);
            if (userDto != null)
            {
                SiteMaps.Current.CurrentNode.ParentNode.Title = userDto.Name;
                var user = Mapper.Map<UserProfile, UserProfileViewModel>(userDto);
                return View(user);
            }
            else
                return HttpNotFound("User not found.");
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmation(int id)
        {
            UserProfile userDto = userService.GetUserById(id);
            if (userDto == null)
                return HttpNotFound();
            if (userService.DeleteUser(userDto.Id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }
        }
        [Route("~/user/{id:int}/profile-picture")]
        public ActionResult GetProfileImage(int id, string placeHolder)
        {
            UserProfile userDto = userService.GetUserById(id);
            string DefaultImage = "~/Content/img/no-image.jpg";

            var user = Mapper.Map<UserProfile,UserProfileViewModel>(userDto);

            if (user == null || user.Photo == null)
            {
                if (string.IsNullOrEmpty(placeHolder))
                {
                    
                    string mime = MimeTypeMap.GetMimeType(System.IO.Path.GetExtension(HttpContext.Server.MapPath(DefaultImage)));
                    byte[] data = System.IO.File.ReadAllBytes(HttpContext.Server.MapPath(DefaultImage));
                    return File(data, mime);
                }
                else
                {
                    string mime = MimeTypeMap.GetMimeType(System.IO.Path.GetExtension(placeHolder));
                    byte[] data = System.IO.File.ReadAllBytes(HttpContext.Server.MapPath(placeHolder));
                    return File(data, mime);
                }
            }

            

            return File(user.Photo.ImageData, "image/png");
        }


        [Route("~/download-report")]
        public ActionResult DownloadReport()
        {
            ReportFileModel report = userService.GenerateReport();
            return File(report.ReportData, report.MimeType, report.FileName);
        }

    }
}

UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Views/Users/CreateUser.cshtml
@model UsersAwardsApp.PLAttributes.Models.UserProfileViewModel

@{
    Layout = "~/Views/Shared/_UsersLayout.cshtml";
    ViewBag.Title = "Create new user";
}

<div class="row">

    <div class="form-container col-md-6 col-md-offset-3 no-padding">
        <div class="form-header">
            <div class="form-title">
                <h2>@ViewBag.Title</h2>
            </div>
        </div>
        <div class="form-content">
            @using (Html.BeginForm("CreateUser", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.BirthDate,new { htmlAttributes = new { @class = "form-control" }  })
                            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "label validation-error" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            <input type="file" name="file" id="file" class="form-control" style="width: 100%;" />
                            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-6">
                            <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                <div class="btn-group">
                                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                                </div>
                                <div class="btn-group">
                                    <input type="submit" value="Create user" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Views/Users/Delete.cshtml
@model UsersAwardsApp.PLAttributes.Models.UserProfileViewModel

@{
    Layout = "~/Views/Shared/_UsersLayout.cshtml";
    ViewBag.Title = "Delete user "+Model.Name;
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-danger">
            <div class="panel-heading">
                Are you sure you want to delete this user profile?
            </div>
            <div class="panel-body clearfix">
                <div class="row">

                    <div class="col-md-2">
                        <img src="@Url.Action("GetProfileImage",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="" class="user-small-img" />
                    </div>
                    <div class="col-md-10">
                        <div class="form-group">
                            <div class="control-label col-md-3 text-right">
                                <b>@Html.DisplayNameFor(x => x.Name):</b>
                            </div>
                            <div class="col-md-9 text-left">
                                @Html.DisplayFor(x => x.Name)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="control-label col-md-3 text-right">
                                <b>@Html.DisplayNameFor(x => x.BirthDate):</b>
                            </div>
                            <div class="col-md-9 text-left">
                                @Html.DisplayFor(x => x.BirthDate)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="control-label col-md-3 text-right">
                                <b>@Html.DisplayNameFor(x => x.Age):</b>
                            </div>
                            <div class="col-md-9 text-left">
                                @Html.DisplayFor(x => x.Age)
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group clearfix">
                <div class="btn-group pull-right">
                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>

UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Views/Users/Edit.cshtml
@model UsersAwardsApp.PLAttributes.Models.UserProfileViewModel

@{
    Layout = "~/Views/Shared/_UsersLayout.cshtml";
    ViewBag.Title = "Edit user - " + Model.Name;
}

<div class="row">

    <div class="form-container col-md-6 col-md-offset-3 no-padding">
        <div class="form-header">
            <div class="form-title">
                <h2>@ViewBag.Title</h2>
            </div>
        </div>
        <div class="form-content">
            @using (Html.BeginForm("Edit", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = Html.NameFor(x => x.Name) } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.BirthDate, new {htmlAttributes = new { @class = "form-control" } } )
                            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "label validation-error" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            <div class="row">

                                <div class="col-md-4">
                                    <div class="profile-image">
                                        <img src="@Url.Action("GetProfileImage",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="" class="profile-image-content" />
                                    </div>
                                </div>

                                <div class="col-md-8">
                                    <div class="input-group">
                                        <input type="file" name="file" id="file" class="form-control" />
                                        <span class="input-group-btn">
                                            <a href="@Url.Action("RemoveImage","Users",new { userId = Model.Id })" class="btn btn-danger @Helpers.BoolCompare(!ViewBag.HasImage,"disabled") ">Remove image</a>
                                        </span>
                                    </div>
                                    
                                </div>
                            </div>
                            

                            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 btn-group btn-group-justified" role="group" aria-label="...">
                            <div class="btn-group">
                                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                            </div>
                            <div class="btn-group">
                                <input type="submit" value="Save changes" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Views/Users/Index.cshtml
@model IEnumerable<UsersAwardsApp.PLAttributes.Models.UserProfileViewModel>

@{
    Layout = "~/Views/Shared/_UsersLayout.cshtml";
    ViewBag.Title = "All users";
}

@section Scripts {
    
}

@section Modal{
    @Helpers.CustomModal("AwardModal", false)
    @Helpers.CustomModal("ErrorModal", true)
}
@section Heading{
    <div class="header-buttons btn-group pull-right">
        <a href="@Url.Action("CreateUser","Users",null)" class="btn btn-sm btn-success">
            <i class="fa fa-plus"></i>
        </a>

        <a href="@Url.Action("DownloadReport","Users",null)" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title="Download report">
            <i class="fa fa-download"></i>
        </a>
    </div>
}
@section Search{
    <div class="row clearfix">
        <div class="panel panel-default">
            <div class="panel-body">
                @using (Html.BeginForm("Index", "Users", FormMethod.Get, new { id = "SearchForm" }))
                {
                    <div class="input-group">
                        @Html.TextBox("term", null, new { id = "SearchField", placeholder = "Search ...", @class = "form-control input-sm" })
                        <span class="input-group-btn">
                            <button type="reset" class="btn btn-default btn-sm" id="ClearSearch">
                                <span class="fa fa-close" aria-hidden="true"></span>
                            </button>
                            <button class="btn btn-default btn-sm" type="submit">
                                <span class="fa fa-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div><!-- /input-group -->
                }
            </div>
        </div>
    </div><!-- /.row -->
}


    <div class="row">
        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                @Html.Partial("_UserProfilePartial", item);
            }
        }
        else
        {
            <div class="alert alert-danger" role="alert">
                No users were found. 
            </div>
        }
        <div id="modal-background"></div>
    </div>

UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Views/Users/UserPage.cshtml
@model UsersAwardsApp.PLAttributes.Models.UserProfileViewModel

@{
    Layout = "~/Views/Shared/_UsersLayout.cshtml";
    ViewBag.Title = Model.Name;
}
@section Modal{
    @Helpers.CustomModal("AwardModal", false)
    @Helpers.CustomModal("ErrorModal", true)
}
<div class="row">

    <div class="panel panel-default">
        <div class="panel-body userpage-card clearfix">
            <div class="profile-image">
                <img src="@Url.Action("GetProfileImage",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="" class="profile-image-content" />

            </div>
            <div class="profile-desc">
                <div class="profile-name">@Html.DisplayFor(model => model.Name)</div>
                <div>
                    <b>Birth Date:</b> @string.Format("{0:dd.MM.yyyy}", Model.BirthDate)
                </div>
                <div>
                    <b>Age:</b> @Model.Age
                </div>
                <hr />
                <div class="awards-list">
                    @Html.Action("GetAwardsForUser", "Awards", new { id = Model.Id })
                </div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <div class="btn-group pull-right">
                @Html.ActionLink("Edit", "Edit", new { userId = Model.Id }, new { @class = "btn btn-sm btn-default" })
                @Html.ActionLink("Delete", "Delete", new { userId = Model.Id }, new { @class = "btn btn-sm btn-default" })
                @Html.ActionLink("Give an award", "ChooseAward", "Awards", new { userId = Model.Id }, new { @class = "btn btn-sm btn-success" })
            </div>
        </div>
    </div>


</div>

UsersAwardsApp MVC5/UsersAwardsApp.PLAttributes/Views/Users/_UserProfilePartial.cshtml
@model UsersAwardsApp.PLAttributes.Models.UserProfileViewModel

<div class="col-md-4 no-padding card-holder">
    <div class="user-card">
        <div class="panel-body">
            <div class="profile-image">
                <img src="@Url.Action("GetProfileImage","Users",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="" class="profile-image-content" />
            </div>
            <div class="profile-desc">
                <span class="user-name"><a href="@Url.Action("UserPage","Users",new { userId = Model.Id})">@Html.DisplayFor(modelItem => modelItem.Name)</a></span>
                <div><b>Birth Date:</b> @string.Format("{0:dd}.{0:MM}.{0:yyy}", Model.BirthDate)</div>
                <div><b>Age:</b> @Html.DisplayFor(modelItem => modelItem.Age)</div>
            </div>
        </div>
        <div class="panel-footer clearfix">
            <span class="btn-group btn-group-xs pull-right">
                <a href="@Url.Action("Edit", new { userId = Model.Id })" class="btn btn-primary">
                    <i class="fa fa-cog"></i>
                    <span class="sr-only">Edit</span>
                </a>
                @Ajax.IconAjaxLink("fa fa-trash-o", "Delete user", "DeleteAjax", new { userId = Model.Id }, new { @class = "btn btn-primary" },
                   new AjaxOptions
                   {
                       Confirm = "Are you sure want to delete this user profile?",
                       OnSuccess = "PageModule.ajaxAction.userDeleteSuccess",
                       OnBegin = "PageModule.ajaxAction.userDeleteBegin",
                   })
            </span>

            <div class="btn-group">
                <a href="@Url.Action("UserPage","Users",new { userId = Model.Id})" class="btn btn-primary btn-xs" data-toggle="collapse" data-target="#collapseExample-@Model.Id" aria-expanded="false" aria-controls="collapseExample">Awards</a>
                <a href="@Url.Action("ChooseAward","Awards",new { userId = Model.Id})" class="btn btn-primary btn-xs">
                    <i class="fa fa-plus"></i>
                </a>
            </div>

        </div>

    </div>

    <div class="collapse awards-card" id="collapseExample-@Model.Id">
        <div class="awards-list">
            @Html.Action("GetAwardsForUser","Awards",new { id = Model.Id})
        </div>
    </div>
</div>