UsersAwardsApp MVC5/UsersAwardsApp.PL/Models/Awards/AwardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UsersAwardsApp.PL.Models
{
    public class AwardViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title of award is required")]
        [StringLength(50, ErrorMessage = "Award title should be less than 50 characters")]
        [RegularExpression(@"[a-zA-Z0-9\s-]+", ErrorMessage = "You can use only latin characters for award title")]
        public string Title { get; set; }

        [StringLength(250,ErrorMessage = "Award description should be less than 250 characters")]
        [DisplayFormat(NullDisplayText = "No description for this award")]
        public string Description { get; set; }

        public ImageViewModel Image { get; set; }
        public int UsersCount { get; set; }
    }
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Models/Awards/CreateAwardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UsersAwardsApp.PL.Models
{
    public class CreateAwardViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title of award is required")]
        [StringLength(50, ErrorMessage = "Award title should be less than 50 characters")]
        [RegularExpression(@"[a-zA-Z0-9\s-]+",ErrorMessage = "You can use only latin characters, hyphens and spaces for award title")]
        public string Title { get; set; }

        [StringLength(250,ErrorMessage = "Award description should be less than 250 characters")]
        public string Description { get; set; }
        
        public virtual HttpPostedFileBase Image { get; set; }
    }
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Models/Awards/GiveAwardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UsersAwardsApp.PL.Models
{
    public class GiveAwardViewModel
    {
        public virtual UserProfileViewModel User { get; set; }
        public virtual AwardViewModel Award { get; set; }
    }
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Controllers/AwardsController.cs
using AutoMapper;
using MimeTypes;
using MvcSiteMapProvider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UsersAwardsApp.Entities;
using UsersAwardsApp.LogicContracts;
using UsersAwardsApp.PL.Models;

namespace UsersAwardsApp.PL.Controllers
{
    public class AwardsController : BaseController
    {

        public AwardsController(IAwardService awardService, IUserService userService)
            :base(userService, awardService)
        {

        }

        // GET: Awards
        public ActionResult Index(string term)
        {
            IEnumerable<Award> awards;
            if (!string.IsNullOrWhiteSpace(term))
            {
                SiteMaps.Current.CurrentNode.Description = string.Format("Search by \"{0}\"", term);
                awards = awardService.FindAllByTitle(term);
            }
            else
            {
                awards = awardService.GetAwards();
            }

            var usersView = Mapper.Map<IEnumerable<Award>, IEnumerable<AwardViewModel>>(awards);
            return View(usersView);
        }


        public ActionResult FindByName(string term)
        {
            Award _award = awardService.FindAnyByTitle(term);
            if(_award != null)
            {
                AwardViewModel _awardView = Mapper.Map<Award, AwardViewModel>(_award);
                SiteMaps.Current.CurrentNode.Title = _award.Title;
                return View("AwardInfo", _awardView);
            }else
            {
                return new HttpNotFoundResult("Award not found");
            }
        }

        [HttpGet]
        public ActionResult CreateAward()
        {
            CreateAwardViewModel model = new CreateAwardViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateAward(CreateAwardViewModel model)
        {
            string MimeType = "";
            if (model.Image == null)
            {
                ModelState.AddModelError(nameof(model.Image), "Images is required");
            }
            else
            {
                MimeType = model.Image.ContentType;
                if (!MimeType.Contains("image"))
                    ModelState.AddModelError(nameof(model.Image), "Images only allowed");
            }

            if (ModelState.IsValid)
            {
                byte[] ImageData = new byte[model.Image.ContentLength];
                model.Image.InputStream.Read(ImageData, 0, ImageData.Length);

                AwardViewModel award = new AwardViewModel()
                {
                    Title = model.Title,
                    Description = model.Description,
                    Image = new ImageViewModel() { ImageData = ImageData, Mime = MimeType }
                    
                };
                awardService.CreateAward(Mapper.Map<AwardViewModel, Award>(award));

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [ActionName("Edit")]
        public ActionResult Edit(int id)
        {
            Award awardDto = awardService.GetAwardById(id);
            if (awardDto != null)
            {
                SiteMaps.Current.CurrentNode.ParentNode.Title = awardDto.Title;
                return View(Mapper.Map<Award, AwardViewModel>(awardDto));
            }
            else
                return HttpNotFound("Award not found.");
        }
        [HttpPost]
        public ActionResult Edit(AwardViewModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    byte[] data = new byte[file.ContentLength];
                    file.InputStream.Read(data, 0, data.Length);
                    model.Image = new ImageViewModel() { ImageData = data, Mime = file.ContentType };
                }

                if(awardService.UpdateAward(Mapper.Map<AwardViewModel, Award>(model)))
                {

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Update error");
                    return RedirectToAction("Edit",model);
                }
            }
            else
                return View(model);
        }


        [HttpGet]
        public ActionResult GetAwardImage(int id, string placeHolder)
        {
            var imageDto = awardService.GetAwardImage(id);
            if (imageDto != null)
            {

                ImageViewModel image = Mapper.Map<Image, ImageViewModel>(imageDto);
                return File(image.ImageData, image.Mime);
            }
            else
            {
                if (placeHolder == null) return HttpNotFound();
                string mime = MimeTypeMap.GetMimeType(System.IO.Path.GetExtension(placeHolder));
                byte[] data = System.IO.File.ReadAllBytes(HttpContext.Server.MapPath(placeHolder));
                return File(data, mime);
            }
        }

        [HttpGet]
        public ActionResult ChooseAward(int userId)
        {

            UserProfile userDto = userService.GetUserById(userId);
            if (userDto == null)
                return HttpNotFound();

            UserProfileViewModel userView = Mapper.Map<UserProfile, UserProfileViewModel>(userDto);

            IEnumerable<Award> freeAwardsDto = awardService.GetFreeAwards(userId);

            IEnumerable<AwardViewModel> awardsToShow = Mapper.Map<IEnumerable<Award>, IEnumerable<AwardViewModel>>(freeAwardsDto);

            ViewBag.UserId = userView.Id;
            ViewBag.UserName = userView.Name;

            SiteMaps.Current.CurrentNode.ParentNode.Title = userView.Name;

            return View(awardsToShow);
        }

        [HttpGet]
        public ActionResult ApplyAward(int userId, int awardId)
        {
            UserProfile _userDto = userService.GetUserById(userId);
            UserProfileViewModel _user = Mapper.Map<UserProfile,UserProfileViewModel>(_userDto);


            if (_user == null)
                return HttpNotFound("User not found");

            Award _awardDto = awardService.GetAwardById(awardId);
            AwardViewModel _award = Mapper.Map<Award,AwardViewModel>(_awardDto);

            if (_award == null)
                return HttpNotFound("Award not found");

            SiteMaps.Current.CurrentNode.ParentNode.Title = _user.Name;
            ViewBag.HasAward = _userDto.Awards.Count(x=>x.Id == _awardDto.Id)>0 ? true : false;


            return View(new GiveAwardViewModel() { User = _user, Award = _award });
        }

        [HttpPost]
        [ActionName("ApplyAward")]
        public ActionResult ApplyAwardConfrimed(int userId, int awardId)
        {
            awardService.ApplyAward(userId, awardId);
            return RedirectToAction("Index", "Users", null);
        }

        [HttpGet]
        public ActionResult CancelAward(int userId, int awardId)
        {
            UserProfile _userDto = userService.GetUserById(userId);
            UserProfileViewModel _user = Mapper.Map<UserProfile, UserProfileViewModel>(_userDto);


            if (_user == null)
                return HttpNotFound("User not found");

            Award _awardDto = awardService.GetAwardById(awardId);
            AwardViewModel _award = Mapper.Map<Award, AwardViewModel>(_awardDto);

            if (_award == null)
                return HttpNotFound("Award not found");

            SiteMaps.Current.CurrentNode.ParentNode.Title = _user.Name;
            ViewBag.HasAward = _userDto.Awards.Count(x => x.Id == _awardDto.Id) > 0 ? true : false;


            return View(new GiveAwardViewModel() { User = _user, Award = _award });
        }

        [HttpPost]
        [ActionName("CancelAward")]
        public ActionResult CancelRewardConfirmed(int userId, int awardId)
        {
            awardService.CancelAward(userId, awardId);
            return RedirectToAction("Index", "Users", null);
        }

        public ActionResult GetAwardsForUser(int id)
        {
            UserProfile _user = userService.GetUserById(id);
            ViewBag.UserId = id;
            return PartialView("_AwardsCardPartial",(_user != null) ? Mapper.Map<IEnumerable<Award>,IEnumerable<AwardViewModel>>(awardService.GetAwardForUser(_user.Id)) : null);
        }


        public ActionResult AwardInfo(int id)
        {
            Award _awardDto = awardService.GetAwardById(id);
            if (_awardDto != null)
            {
                SiteMaps.Current.CurrentNode.Title = _awardDto.Title;
                return View(Mapper.Map<Award, AwardViewModel>(_awardDto));
            }
            else
                return HttpNotFound("Award not found");
        }

        [HttpGet]
        public ActionResult GetAwardModal(int awardId,int userId)
        {
            if (!Request.IsAjaxRequest())
                return RedirectToAction("AwardInfo", new { id = awardId });

            Award _awardDto = awardService.GetAwardById(awardId);
            if (_awardDto != null)
            {
                ViewBag.UserId = userId;
                return PartialView("_AwardModalPartial",Mapper.Map<Award, AwardViewModel>(_awardDto));
            }
            else
                return Json(false);
        }


        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            Award awardDto = awardService.GetAwardById(id);
            if (awardDto != null)
            {
                SiteMaps.Current.CurrentNode.ParentNode.Title = awardDto.Title;
                var award = Mapper.Map<Award, AwardViewModel>(awardDto);
                return View(award);
            }
            else
                return HttpNotFound("Award not found.");
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmation(int id)
        {

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/ApplyAward.cshtml
@model UsersAwardsApp.PL.Models.GiveAwardViewModel
@{
    Layout = "~/Views/Shared/_AwardsLayout.cshtml";
    ViewBag.Title = string.Format("Give an award to user {0}", Model.User.Name) ;
}

@if (!ViewBag.HasAward)
{
    <div class="row">
            <div class="panel panel-success">
                <div class="panel-heading">Confirm action</div>
                <div class="panel-body">
                    Are you sure want to give a <a href="@Url.Action("AwardInfo","Awards", new { id = Model.Award.Id})" class="text-parimary text-bold">@Model.Award.Title</a>
                    award to the <a href="@Url.Action("UserPage","Users",new { userId = Model.User.Id})" class="text-parimary text-bold">@Model.User.Name</a>?
                </div>
                <div class="panel-footer clearfix">
                    <div class="btn-group pull-right">
                        @using (Html.BeginForm())
                        {
                            @Html.Hidden("userId", Model.User.Id)
                            @Html.Hidden("awardId", Model.Award.Id)
                            <a href="@Url.Action("Index","Users")" class="btn btn-sm btn-default">Cancel</a>
                            <button type="submit" class="btn btn-sm btn-success">Give an award</button>
                        }
                    </div>
                </div>
            </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-danger">
                <div class="panel-heading">Error</div>
                <div class="panel-body">
                    User <a href="@Url.Action("UserPage","Users",new { id = Model.User.Id})">@Model.User.Name</a> already have an award
                    <a href="@Url.Action("AwardInfo","Awards", new { id = Model.Award.Id})" class="text-success text-bold">@Model.Award.Title</a>
                </div>
                <div class="panel-footer clearfix">
                    <div class="btn-group pull-right">
                        <a href="@Url.Action("Index","Users")" class="btn btn-sm btn-default">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/AwardInfo.cshtml
@model UsersAwardsApp.PL.Models.AwardViewModel

@{
    Layout = "~/Views/Shared/_AwardsLayout.cshtml";
    ViewBag.Title = "Award - " + Model.Title;
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-success">
            <div class="panel-body clearfix">
                <div class="row">

                    <div class="col-md-2">
                        <img src="@Url.Action("GetAwardImage",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="" class="award-big-img" />
                    </div>
                    <div class="col-md-10">
                        <div class="form-group">
                            <div class="control-label col-md-3 text-right">
                                <b>@Html.DisplayNameFor(x => x.Title):</b>
                            </div>
                            <div class="col-md-9 text-left">
                                @Html.DisplayFor(x => x.Title)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="control-label col-md-3 text-right">
                                <b>@Html.DisplayNameFor(x => x.Description):</b>
                            </div>
                            <div class="col-md-9 text-left">
                                @Html.DisplayFor(x => x.Description)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-9 col-md-offset-3 text-left">
                                <b><a href="@Url.Action("UsersByAward", "Users",new { id = Model.Id })">@Html.DisplayFor(x => x.UsersCount)</a></b> users have this award.
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group clearfix">
                <div class="btn-group pull-right">
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-default" })
                </div>
            </div>
        }
    </div>
</div>

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/CancelAward.cshtml
@model UsersAwardsApp.PL.Models.GiveAwardViewModel
@{
    Layout = "~/Views/Shared/_AwardsLayout.cshtml";
    ViewBag.Title = string.Format("Cancel rewarding for {0}", Model.User.Name) ;
}

@if (ViewBag.HasAward)
{
    <div class="row">
            <div class="panel panel-danger">
                <div class="panel-heading">Confirm action</div>
                <div class="panel-body">
                    Are you sure want to remove award <a href="@Url.Action("AwardInfo","Awards", new { id = Model.Award.Id})" class="text-primary text-bold">@Model.Award.Title</a> from user <a href="@Url.Action("UserPage","Users",new { userId = Model.User.Id})" class="text-primary text-bold">@Model.User.Name</a>?
                </div>
                <div class="panel-footer clearfix">
                    <div class="btn-group pull-right">
                        @using (Html.BeginForm())
                        {
                            @Html.Hidden("userId", Model.User.Id)
                            @Html.Hidden("awardId", Model.Award.Id)
                            <a href="@Url.Action("Index","Users")" class="btn btn-sm btn-default">Cancel</a>
                            <button type="submit" class="btn btn-sm btn-success">Remove award</button>
                        }
                    </div>
                </div>
            </div>
    </div>
}
else
{
    <div class="row">
            <div class="panel panel-danger">
                <div class="panel-heading">Error</div>
                <div class="panel-body">
                    User <a href="@Url.Action("UserPage","Users",new { id = Model.User.Id})">@Model.User.Name</a> has no award
                    <a href="@Url.Action("AwardInfo","Awards", new { id = Model.Award.Id})" class="text-success text-bold">@Model.Award.Title</a>
                </div>
                <div class="panel-footer clearfix">
                    <div class="btn-group pull-right">
                        <a href="@Url.Action("Index","Users")" class="btn btn-sm btn-default">Back</a>
                    </div>
                </div>
            </div>
    </div>
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/ChooseAward.cshtml
@model IEnumerable<UsersAwardsApp.PL.Models.AwardViewModel>

@{
    Layout = "~/Views/Shared/_AwardsLayout.cshtml";
    ViewBag.Title = "Choose award for user " + ViewBag.UserName;
}

<div class="row">
    <div class="col-md-12 no-padding">

        @if (Model.Count() > 0)
        {
                <div class="text-danger">
                    @Html.ValidationSummary()
                </div>

                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4">
                            <div class="panel panel-default">

                                <div class="choose-award">

                                    <img src="@Url.Action("GetAwardImage", new { id = item.Id, placeHolder = "~/Content/img/no-image.jpg" })" class="choose-award-image thumbnail" />
                                    <div class="choose-award-info-block">
                                        <span class="choose-award-title">
                                            <a href="@Url.Action("AwardInfo", "Awards", new { id = item.Id })">@item.Title</a>
                                        </span>
                                        <span class="choose-award-desc">
                                            @Html.DisplayTextFor(x=> item.Description)
                                        </span>
                                    </div>

                                </div>

                                <div class="panel-footer clearfix">
                                    <div class="btn-group pull-right">
                                        @Html.ActionLink("Give this award", "ApplyAward", "Awards", new { userId = ViewBag.UserId, awardId = item.Id }, new { @class = "btn btn-xs btn-success" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>

        }
        else
        {
            <div class="alert alert-danger" role="alert">No available awards for this user</div>
        }
    </div>
</div>

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/CreateAward.cshtml
@model UsersAwardsApp.PL.Models.CreateAwardViewModel

@{
    Layout = "~/Views/Shared/_AwardsLayout.cshtml";
    ViewBag.Title = "Create new award";
}

<div class="row">

    <div class="form-container col-md-6 col-md-offset-3 no-padding">
        <div class="form-header">
            <div class="form-title">
                <h2>@ViewBag.Title</h2>
            </div>
        </div>
        <div class="form-content">
            @using (Html.BeginForm("CreateAward", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "label validation-error" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.TextAreaFor(model => model.Description, 3, 0, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "label validation-error" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">

                            @Html.FileFor(model => model.Image, "form-control")
                            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-6">
                            <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                <div class="btn-group">
                                    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                                </div>
                                <div class="btn-group">
                                    <input type="submit" value="Create award" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>



@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/Edit.cshtml
@model UsersAwardsApp.PL.Models.AwardViewModel

@{
    Layout = "~/Views/Shared/_AwardsLayout.cshtml";
    ViewBag.Title = string.Format("Edit award \"{0}\"", Model.Title);
}

<div class="row">

    <div class="form-container col-md-6 col-md-offset-3 no-padding">
        <div class="form-header">
            <div class="form-title">
                <h2>@ViewBag.Title</h2>
            </div>
        </div>
        <div class="form-content">
            @using (Html.BeginForm("Edit", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = Html.NameFor(x => x.Title) } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            @Html.TextAreaFor(model => model.Description, 3, 0, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "label validation-error" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "col-md-12" })
                        <div class="col-md-12">
                            <div class="row">

                                <div class="col-md-4">
                                    <div class="profile-image">
                                        <img src="@Url.Action("GetAwardImage",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="" class="profile-image-content" />
                                    </div>
                                </div>

                                <div class="col-md-8">
                                    <input type="file" name="file" id="file" class="form-control" />
                                </div>
                            </div>


                            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "label validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 btn-group btn-group-justified" role="group" aria-label="...">
                            <div class="btn-group">
                                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                            </div>
                            <div class="btn-group">
                                <input type="submit" value="Save changes" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/_AwardModalPartial.cshtml
@model UsersAwardsApp.PL.Models.AwardViewModel

<div class="row award-modal">
    <div class="col-md-3">
        <img src="@Url.Action("GetAwardImage",  new { id = Model.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="@Model.Title" class="thumbnail" />
    </div>
    <div class="col-md-9">
        <div class="award-modal-title">
            <a href="@Url.Action("AwardInfo","Awards", new { id = Model.Id })" class="text-bold">
                @Model.Title
            </a>
        </div>

        <div class="award-modal-desc">
            @Html.DisplayText("Description")
        </div>
        <hr />
        <div class="award-modal-desc">
            <a href="@Url.Action("CancelAward","Awards",new { awardId = Model.Id, userId = ViewBag.UserId })" class="pull-right">Remove award from user</a>
            <b><a href="@Url.Action("UsersByAward", "Users",new { id = Model.Id })">@Model.UsersCount</a> users have this award.</b>
        </div>
    </div>
</div>

UsersAwardsApp MVC5/UsersAwardsApp.PL/Views/Awards/_AwardsCardPartial.cshtml
@model IEnumerable<UsersAwardsApp.PL.Models.AwardViewModel>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class="award-thumbnail">
            <a href="@Url.Action("GetAwardModal","Awards",new { awardId= item.Id, userId = ViewBag.UserId })" class="thumbnail" data-toggle="tooltip" data-placement="top" title="@item.Title" data-load-award="@item.Id">
                <img src="@Url.Action("GetAwardImage",  new { id = item.Id, placeHolder = "~/Content/img/no-image.jpg" })" alt="@item.Title" class="" />
            </a>
        </div>

    }
}
else
{
    <div>User has no awards</div>
}